import { v4 as uuid } from 'uuid'
console.log(uuid())

export const story3Statements = [
  {
    id: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
    image: "https://raw.githubusercontent.com/muhiddinjv/poc/refs/heads/main/public/img/horseman.jpg",
    statement: "Hay un jinete",
    stranslation: "There is a horseman",
  },
  {
    id: "3d3a5fe2-2308-4e35-aa7c-70a4916cb9ee",
    image: "https://raw.githubusercontent.com/muhiddinjv/poc/refs/heads/main/public/img/headless_horseman.jpg", 
    statement: "Hay un jinete sin cabeza",
    stranslation: "There is a horseman without head",
  },
];

export const story3Questions = [
  //Hay un jinete sin cabeza-------------------------------------
  {
    id: "f1fdc9ea-012d-48f2-a511-dcaf971d478a",
    statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
    question: "Hay un jinete?",
    qtranslation: "Is there a horseman?",
    answer: "sí",
    image: "https://picsum.photos/500",
    feedback: "Hay un jinete.",
    explanation: "This is the question and 'Hay' means 'There is'",
    point: 20,
  },
  {
    id: "36927105-3295-49dc-8af9-bd10d4381d8f",
    statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
    question: "¿Hay un chico?",
    qtranslation: "Is there a boy?",
    answer: "No",
    image: "https://picsum.photos/499",
    feedback: "No hay un chico. Hay un jinete.",
    explanation: "'Un' is the word 'a' in English",
    point: 20,
  },
  //Hay un jinete sin cabeza-------------------------------------
  {
    id: "3a7a681c-79a8-4ea7-a989-638b95d7835f",
    statementId: "3d3a5fe2-2308-4e35-aa7c-70a4916cb9ee",
    question: "Hay un jinete sin cabeza?",
    qtranslation: "Is there a horseman without a head?",
    image: "https://picsum.photos/495",
    answer: "sí",
    feedback: "Hay un jinete sin cabeza.",
    explanation: "'sin' means 'without' in English",
    point: 20,
  },
  {
    id: "39a82fdd-c208-4ce9-89c8-78cbd3e8dfe0", 
    statementId: "3d3a5fe2-2308-4e35-aa7c-70a4916cb9ee",
    question: "¿Hay un jinete sin cabeza o con cabeza?",
    qtranslation: "Is there a horseman without a head or with a head?",
    image: "https://picsum.photos/495",
    answer: "sin cabeza",
    feedback: "Hay un jinete sin cabeza.",
    explanation: "'con' means 'with' in English",
    point: 20,
  },  
  {
    id: "7a7e34ca-c14f-4c99-baf3-c2c547e984f6",
    statementId: "3d3a5fe2-2308-4e35-aa7c-70a4916cb9ee",
    question: "¿Hay un jinete con cabeza?",
    qtranslation: "Is there a horseman with a head?",
    image: "https://picsum.photos/493",
    answer: "no",
    feedback: "No hay un jinete con cabeza. Hay un jinete sin cabeza.",
    explanation: "",
    point: 20,
  },
]

// TEST data below
export const story1Statements = [
  {
    id: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
    image: "https://raw.githubusercontent.com/muhiddinjv/poc/refs/heads/main/public/img/horseman.jpg",
    statement: "Hay un jinete",
    stranslation: "There is a horseman",
  },
  {
    id: "3d3a5fe2-2308-4e35-aa7c-70a4916cb9ee",
    image: "https://raw.githubusercontent.com/muhiddinjv/poc/refs/heads/main/public/img/headless_horseman.jpg", 
    statement: "Hay un jinete sin cabeza",
    stranslation: "There is a horseman without head",
  },
  {
    id: "540d7cfe-7351-4d79-9739-f51722b796f3",
    image: "https://raw.githubusercontent.com/muhiddinjv/poc/refs/heads/main/public/img/headless_horseman.jpg", 
    statement: "El jinete es famoso",
    stranslation: "The horseman is famous",
  },
  {
    id: "3ebda685-1915-4748-a1aa-259550e00e92",
    image: "https://raw.githubusercontent.com/muhiddinjv/poc/refs/heads/main/public/img/headless_horseman_speech.jpg", 
    statement: "Yo soy el jinete",
    stranslation: "I am the horseman",
  },
  {
    id: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    image: "https://raw.githubusercontent.com/muhiddinjv/poc/refs/heads/main/public/img/problem.jpg", 
    statement: "El jinete tiene un problema.",
    stranslation: "The horseman has a problem.",
  },
  {
    id: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    image: "https://raw.githubusercontent.com/muhiddinjv/poc/refs/heads/main/public/img/problem.jpg", 
    statement: "Él va al doctor.",
    stranslation: "He goes to the doctor.",
  },
  // {
  //   id: "f1a9f37d-e919-4046-a754-f5d17d8679cd",
  //   image: "https://raw.githubusercontent.com/muhiddinjv/poc/refs/heads/main/public/img/problem.jpg", 
  //   statement: 'El doctor dice: "¿Cuál es tu problema?"',
  //   stranslation: "The doctor says, 'Whats your problem?'",
  // },
  // {
  //   id: "6fe0021a-07cf-4439-ab45-9bbb56748068",
  //   image: "https://raw.githubusercontent.com/muhiddinjv/poc/refs/heads/main/public/img/problem.jpg", 
  //   statement: "El jinete sin cabeza dice: 'Tengo un dolor de cabeza.'",
  //   stranslation: "The headless horseman says, 'I have a headache.'",
  // },
];

export const story1Questions = [
  //Hay un jinete sin cabeza-------------------------------------
  {
    id: "d8ba9b39-b86a-4c92-a721-daafa0f304ee",
    statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
    question: "Hay un jinete?",
    qtranslation: "Is there a horseman?",
    answer: "sí",
    image: "https://picsum.photos/500",
    feedback: "Hay un jinete.",
    explanation: "This is the question and 'Hay' means 'There is'",
    point: "20",
  },
  {
    id: "0ceedc61-fd58-4cd5-a8f1-d5763252e30b",
    statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
    question: "¿Hay un chico?",
    qtranslation: "Is there a boy?",
    answer: "No",
    image: "https://picsum.photos/499",
    feedback: "No hay un chico. Hay un jinete.",
    explanation: "'Un' is the word 'a' in English",
    point: "20",
  },
  {
    id: "74e3ae48-9e2b-496a-9058-ec4faba32eca",
    statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
    question: "¿Hay una chica?",
    qtranslation: "Is there a girl?",
    answer: "No",
    image: "https://picsum.photos/498",
    feedback: "No hay una chica. Hay un jinete.",
    explanation: "'Una' too is the word 'a'",
    point: "20",
  },
  {
    id: "635d84d2-6378-45d9-8f07-110dd460e702",
    statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
    question: "¿Hay una chica o un jinete?",
    qtranslation: "Is there a girl or a horseman?",
    answer: "jinete",
    image: "https://picsum.photos/497",
    feedback: "Hay un jinete.",
    explanation: "'O' means 'or'",
    point: 20,
  },
  {
    id: "dc2e1d10-78c8-4543-86b0-ace4fff48172",
    statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
    question: "Hay un presidente?",
    qtranslation: "Is there a president?",
    answer: "no",
    image: "https://picsum.photos/496",
    feedback: "No hay un presidente. Hay un jinete.",
    explanation: "'Presidente' means 'president'",
    point: 20,
  },
  //Hay un jinete sin cabeza-------------------------------------
  {
    id: "93fcafaa-8610-4966-8cdb-c09b8a170b64",
    statementId: "3d3a5fe2-2308-4e35-aa7c-70a4916cb9ee",
    question: "Hay un jinete sin cabeza?",
    qtranslation: "Is there a horseman without a head?",
    image: "https://picsum.photos/495",
    answer: "sí",
    feedback: "Hay un jinete sin cabeza.",
    explanation: "'sin' means 'without' in English",
    point: 20,
  },
  {
    id: "10a8df53-b409-4d5e-a434-c1ef774952d6",
    statementId: "3d3a5fe2-2308-4e35-aa7c-70a4916cb9ee",
    question: "¿Hay un jinete sin cabeza o con cabeza?",
    qtranslation: "Is there a horseman without a head or with a head?",
    image: "https://picsum.photos/495",
    answer: "sin cabeza",
    feedback: "Hay un jinete sin cabeza.",
    explanation: "'con' means 'with' in English",
    point: 20,
  },
  {
    id: "7a7e34ca-c14f-4c99-baf3-c2c547e984f6",
    statementId: "3d3a5fe2-2308-4e35-aa7c-70a4916cb9ee",
    question: "¿Hay un jinete con cabeza?",
    qtranslation: "Is there a horseman with a head?",
    image: "https://picsum.photos/493",
    answer: "no",
    feedback: "No hay un jinete con cabeza. Hay un jinete sin cabeza.",
    explanation: "",
    point: 20,
  },
  {
    id: "67b58138-3a6a-433a-804f-3a7c51f9a6e6",
    statementId: "3d3a5fe2-2308-4e35-aa7c-70a4916cb9ee",
    question: "¿Qué hay?",
    qtranslation: "What is there?",
    image: "https://picsum.photos/492",
    answer: "jinete",
    feedback: "Hay un jinete sin cabeza.",
    explanation: "",
    point: 20,
  },
  //El jinete es famoso-------------------------------------
  {
    id: "5b0873d3-b6b9-419b-943a-54d7fb84a7ee",
    statementId: "540d7cfe-7351-4d79-9739-f51722b796f3",
    question: "¿Es el jinete famoso?",
    qtranslation: "Is the horseman famous?",
    image: "https://picsum.photos/491",
    answer: "sí",
    feedback: "El jinete es famoso.",
    explanation: "'Es' means 'is' in English",
    point: 20,
  },
  {
    id: "0d745cb1-4115-436e-8d67-dec2956ee439",
    statementId: "540d7cfe-7351-4d79-9739-f51722b796f3",
    question: "¿Es él famoso o terrible?",
    qtranslation: "Is he famous or terrible?",
    image: "https://picsum.photos/490",
    answer: "famoso",
    feedback: "Él es famoso",
    explanation: "'Él es' literally means 'He he is' so you can simply say 'Es'",
    point: 20,
  },
  {
    id: "429e32dd-035d-4454-9e35-50767f27c650",
    statementId: "540d7cfe-7351-4d79-9739-f51722b796f3",
    question: "¿Es él terrible?",
    qtranslation: "Is he terrible?",
    image: "https://picsum.photos/489",
    answer: "no",
    feedback: "Él no es terrible. Es famoso.",
    explanation: "'no es' means 'is not' in English",
    point: 20,
  },
  //NO IMAGE BELOW-------------------------------------------
  {
    id: "d3545296-56c9-4434-a6b2-b6b21808b4b0",
    statementId: "540d7cfe-7351-4d79-9739-f51722b796f3",
    question: "¿Es Enrique Iglesias famoso?",
    qtranslation: "Is Enrique Iglesias famous?",
    answer: "sí",
    feedback: "Él es famoso.",
    explanation: "",
    point: 20,
  },
  {
    id: "ae1bca8c-7908-43c9-9e29-7bed950c85c1",
    statementId: "540d7cfe-7351-4d79-9739-f51722b796f3",
    question: "¿Es él un jinete?",
    qtranslation: "Is he a horseman?",
    answer: "no",
    feedback: "Es ridiculo! No es un jinete.",
    explanation: "'No es' means '(he) is not' in English",
    point: 20,
  },
  {
    id: "1523d977-2c81-484f-a7e6-eaa324a2ee49",
    statementId: "540d7cfe-7351-4d79-9739-f51722b796f3",
    question: "¿Es el jinete Enrique?",
    qtranslation: "Is the horseman Enrique?",
    answer: "no",
    feedback: "Es ridiculo! El jinete no es Enrique.",
    explanation: "'No es' means '(he) is not' in English",
    point: 20,
  },
  {
    id: "1de0e6b4-56c6-49b3-b10f-13bece36ef06",
    statementId: "540d7cfe-7351-4d79-9739-f51722b796f3",
    question: "¿Es Enrique terrible?",
    qtranslation: "Is Enrique terrible?",
    answer: "no",
    feedback: "No es terrible. Es famoso.",
    explanation: "'No es' means '(he) is not' in English",
    point: 20,
  },
  {
    id: "8cd3b5fa-8ed7-4090-9baf-53e8c371ee36",
    statementId: "540d7cfe-7351-4d79-9739-f51722b796f3",
    question: "¿Es él famoso o terrible?",
    qtranslation: "Is he famous or terrible?",
    answer: "famoso",
    feedback: "Es famoso",
    explanation: "'famoso' means 'famous' in English",
    point: 20,
  },
  {
    id: "c72645e4-f2df-46a7-b300-e82a04c50fe1",
    statementId: "540d7cfe-7351-4d79-9739-f51722b796f3",
    question: "¿Es el jinete famoso?",
    qtranslation: "Is the horseman famous?",
    answer: "sí",
    feedback: "El jinete es famoso.",
    explanation: "'Es' means 'is' in English",
    point: 20,
  },
  // yo soy el jinete ------------------------------------
  {
    id: "df15112f-a3e1-4667-987e-3dd60d93b918",
    statementId: "3ebda685-1915-4748-a1aa-259550e00e92",
    question: "¿Soy el jinete?",
    qtranslation: "am I the horseman?",
    answer: "sí",
    feedback: "Soy el jinete",
    explanation: "'yo soy' means 'I I am' so you can leave out 'yo'",
    point: 20,
  },
  {
    id: "ba914a17-d05e-4683-8b3c-c3e5bcc53859",
    statementId: "3ebda685-1915-4748-a1aa-259550e00e92",
    question: "¿Soy el jinete o un presidente?",
    qtranslation: "am I the horseman or a president?",
    answer: "jinete",
    feedback: "Soy el jinete",
    explanation: "'un presidente' means 'a president' in English",
    point: 20,
  },
  {
    id: "c1d48928-ea08-4f69-9b4d-931f8b86ca54",
    statementId: "3ebda685-1915-4748-a1aa-259550e00e92",
    question: "¿Soy famoso?",
    qtranslation: "am I famous?",
    answer: "sí",
    feedback: "Soy famoso",
    explanation: "",
    point: 20,
  },
  {
    id: "92e8f19e-988a-4fc6-81c2-7391f112e201",
    statementId: "3ebda685-1915-4748-a1aa-259550e00e92",
    question: "¿Soy terrible o famoso?",
    qtranslation: "am I terrible or famous?",
    answer: "famoso",
    feedback: "Soy famoso",
    explanation: "",
    point: 20,
  },
  {
    id: "60c1ce84-be6d-414f-99ea-6d9ba2fd4910",
    statementId: "3ebda685-1915-4748-a1aa-259550e00e92",
    question: "¿Soy terrible?",
    qtranslation: "am I terrible?",
    answer: "no",
    feedback: "No soy terrible. Soy famoso",
    explanation: "'no soy' literally means 'not I am'",
    point: 20,
  },
  {
    id: "12de42c6-7fe3-406d-b39a-4f8627774d7c",
    statementId: "3ebda685-1915-4748-a1aa-259550e00e92",
    question: "¿Soy un presidente?",
    qtranslation: "am I a president?",
    answer: "no",
    feedback: "No soy un presidente. Soy el jinete",
    explanation: "",
    point: 20,
  },
  {
    id: "a8d26003-b064-4a5f-b0ac-fa5cbf7dd0e0",
    statementId: "3ebda685-1915-4748-a1aa-259550e00e92",
    question: "¿Soy el jinete?",
    qtranslation: "am I the horseman?",
    answer: "sí",
    feedback: "Soy el jinete",
    explanation: "",
    point: 20,
  },
  {
    id: "496f6486-dbd6-47fa-aaa8-b339dcacf0c5",
    statementId: "3ebda685-1915-4748-a1aa-259550e00e92",
    question: "¿Soy el jinete con cabeza?",
    qtranslation: "am I the horseman with a head?",
    answer: "no",
    feedback: "No soy el jinete con cabeza. Soy el jinete sin cabeza.",
    explanation: "'con' means 'with' but 'sin' means 'without'",
    point: 20,
  },
  {
    id: "af3c764b-2b4a-4463-895d-72da33bdef98",
    statementId: "3ebda685-1915-4748-a1aa-259550e00e92",
    question: "¿Soy el jinete sin cabeza?",
    qtranslation: "am I the horseman without head?",
    answer: "sí",
    feedback: "Soy el jinete sin cabeza.",
    explanation: "",
    point: 20,
  },
  {
    id: "b4c8f3f6-05c6-49eb-9a11-51c0b7f5ad44",
    statementId: "3ebda685-1915-4748-a1aa-259550e00e92",
    question: "¿Qué soy?",
    qtranslation: "what am I?",
    answer: "jinete",
    feedback: "Soy el jinete",
    explanation: "'¿Qué' means 'what' in English",
    point: 20,
  },
  // El jinete tiene un problema------------------------------------
  {
    id: "940f75a4-cd65-4997-bd26-5d848ba33bce",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿El jinete tiene un problema?",
    qtranslation: "Does the horseman have a problem?",
    answer: "sí",
    feedback: "Él tiene un problema",
    explanation: "'Él tiene' means 'he he has' in English so you can simply say 'tiene' ",
    point: 20,
  },
  {
    id: "2899fa58-d432-4417-bf3b-ec726f6bcb32",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Él tiene un solución?",
    qtranslation: "Does he have a solution?",
    answer: "no",
    feedback: "No él tiene una solución. Tiene un problema",
    explanation: "'Tiene' means 'he has' in English",
    point: 20,
  },
  {
    id: "90ff90cc-b20e-4ef1-9cce-0e6ddfa60756",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Tiene un problema o tiene una solución?",
    qtranslation: "Does he have a problem or does he have a solution?",
    answer: "problema",
    feedback: "No tiene una solución. Tiene un problema",
    explanation: "",
    point: 20,
  },
  {
    id: "1b66c8a5-7edc-4e19-a84d-94f486622012",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Enrique tiene un problema?",
    qtranslation: "Does Enrique have problem?",
    answer: "no",
    feedback: "No tiene un problema",
    explanation: "",
    point: 20,
  },
  {
    id: "88d998d2-3310-4936-8d5b-39047b1a6bfe",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Tiene un micrófono?",
    qtranslation: "Does he have a microphone?",
    answer: "sí",
    feedback: "Tiene un micrófono",
    explanation: "",
    point: 20,
  },
  {
    id: "58fdca72-886a-4ec9-9ff1-04ac63b4dcb5",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Tiene un problema?",
    qtranslation: "Does he have a problema?",
    answer: "no",
    feedback: "No tiene un problema. Tiene un micrófono.",
    explanation: "",
    point: 20,
  },
  {
    id: "11b785db-d2ff-432c-b6f3-a6756d7190bb",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Tiene un problema o tiene un micrófono?",
    qtranslation: "Does he have a problema or does he have a microphone?",
    answer: "micrófono",
    feedback: "Tiene un micrófono.",
    explanation: "",
    point: 20,
  },
  {
    id: "dd2c1245-fb08-4b78-a9bc-90bc56fe9d7f",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Qué tiene?",
    qtranslation: "What does he have?",
    answer: "micrófono",
    feedback: "Tiene un micrófono.",
    explanation: "'Qué' means 'what' in English",
    point: 20,
  },
  {
    id: "2c57f603-37c5-49a4-aa92-13875f2a49f5",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Quién tiene un problema?",
    qtranslation: "Who has a problem?",
    answer: "jinete",
    feedback: "El jinete tiene un problema",
    explanation: "'Quién' means 'who' in English",
    point: 20,
  },
  {
    id: "c40039bb-db57-427e-96d5-6ba8e7a0b167",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Quién no tiene un problema?",
    qtranslation: "Who doesn't have a problem?",
    answer: "Enrique",
    feedback: "Enrique no tiene un problema",
    explanation: "'No tiene' means 'doesnt have' in English",
    point: 20,
  },
  {
    id: "d9d587e9-55fe-4517-85b2-a4e0a5e2c32f",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Quién no tiene un micrófono?",
    qtranslation: "Who doesn't have a microphone?",
    answer: "jinete",
    feedback: "El jinete no tiene un micrófono",
    explanation: "",
    point: 20,
  },
  {
    id: "64715dff-d19a-44e3-b27c-d8077dbf1d41",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Qué tiene el jinete?",
    qtranslation: "What does the horseman have?",
    answer: "problema",
    feedback: "Tiene un problema",
    explanation: "'Qué tiene' means 'what does (he) have' in English",
    point: 20,
  },
  {
    id: "13a3b249-2351-41b8-a646-37c3ef19f427",
    statementId: "73d94834-3309-4114-bbd7-b1c9bac22e17",
    question: "¿Qué tiene Enrique?",
    qtranslation: "What does Enrique have?",
    answer: "micrófono",
    feedback: "Tiene un micrófono",
    explanation: "",
    point: 20,
  },
  // Va al doctor ------------------------------------------
  {
    id: "28604354-94f0-475e-9faf-c704108250e1",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Él va al doctor?",
    qtranslation: "Does he go to the doctor?",
    answer: "sí",
    feedback: "Va al doctor",
    explanation: "'Él va' literally means 'he he goes' in English so you can leave out the 'Él' if you want",
    point: 20,
  },
  {
    id: "41048d12-b9d5-46eb-87a3-ec6fb836962d",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Él va al doctor o al presidente?",
    qtranslation: "Does he go to the doctor or the president?",
    answer: "doctor",
    feedback: "Va al doctor",
    explanation: "",
    point: 20,
  },
  {
    id: "2737bf73-f202-4bbb-9d6a-e13e05bd5cfe",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Él va al presidente?",
    qtranslation: "Does he go to the president?",
    answer: "no",
    feedback: "No va al presidente. Va al doctor",
    explanation: "",
    point: 20,
  },
  {
    id: "7fa6a59b-eff2-49ea-9922-2122d7bcb19f",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Va Enrique a un concierto?",
    qtranslation: "Does Enrique go to a concert?",
    answer: "sí",
    feedback: "Va a un concierto.",
    explanation: "",
    point: 20,
  },
  {
    id: "954917ef-a920-4d97-8815-a4bb4390c31c",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Va el jinete a un concierto?",
    qtranslation: "Does the horseman go to a concert?",
    answer: "no",
    feedback: "No va a un concierto. Va al doctor.",
    explanation: "",
    point: 20,
  },
  {
    id: "9bde76e3-c428-4b75-aecc-32c111e5f6fc",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Él va al doctor?",
    qtranslation: "Does he go to the doctor?",
    answer: "sí",
    feedback: "Va al doctor.",
    explanation: "",
    point: 20,
  },
  {
    id: "7bd01ff3-42ff-47ec-b200-30473fe79624",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Él va al presidente?",
    qtranslation: "Does he go to the president?",
    answer: "no",
    feedback: "No va al presidente. Va al doctor",
    explanation: "",
    point: 20,
  },
  {
    id: "6b8e0a85-dab6-454e-b3c7-0c71d1889bad",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Va Enrique a un concierto?",
    qtranslation: "Does Enrique go to a concert?",
    answer: "sí",
    feedback: "Va a un concierto.",
    explanation: "",
    point: 20,
  },
  {
    id: "018ddf5f-0742-4ded-a8b1-8d3a085af513",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Él va a un concierto o al doctor?",
    qtranslation: "Does he go to a concert or the doctor?",
    answer: "concierto",
    feedback: "Va a un concierto.",
    explanation: "",
    point: 20,
  },
  {
    id: "bf1784f5-f293-47a2-ac8c-8da8a3772c11",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Va Enrique al doctor o va el jinete al doctor?",
    qtranslation: "Does Enrique go to the doctor or does the horseman go to the doctor?",
    answer: "jinete",
    feedback: "El jinete va al doctor.",
    explanation: "",
    point: 20,
  },
  {
    id: "a9887e63-be15-468c-b9a0-239f4e75245f",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Va el jinete al doctor o a un concierto?",
    qtranslation: "Does the horseman go to the doctor or does he go to a concert?",
    answer: "doctor",
    feedback: "El jinete va al doctor.",
    explanation: "",
    point: 20,
  },
  {
    id: "a8e5f8cf-2de8-4983-9f4b-5135040754cc",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Quién va al doctor?",
    qtranslation: "Who goes to the doctor?",
    answer: "jinete",
    feedback: "El jinete va al doctor.",
    explanation: "",
    point: 20,
  },
  {
    id: "6de1018a-536c-467b-ba20-b3d455c14232",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿Quién va a un concierto?",
    qtranslation: "Who goes to a concert?",
    answer: "Enrique",
    feedback: "Enrique va a un concierto.",
    explanation: "",
    point: 20,
  },
  {
    id: "8d9ed5b0-42e5-4f7b-aa50-a1df01ccfe44",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿A dónde va el jinete?",
    qtranslation: "Where does the horseman go?",
    answer: "doctor",
    feedback: "Va al doctor.",
    explanation: "",
    point: 20,
  },
  {
    id: "a9c24863-3caa-47b7-9be3-00e9915613c2",
    statementId: "0b8e3531-300a-4fcb-8d59-549bdeb82a7b",
    question: "¿A dónde va Enrique?",
    qtranslation: "Where does Enrique go?",
    answer: "concierto",
    feedback: "Va a un concierto.",
    explanation: "",
    point: 20,
  },
]

export const TPRS_2_0 = {
  storyTitle: "El Problema del Chico",
  quizSynopsis: "",
  statements: [
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un chico",
      explanation: "",
      retell: "",
      questions: [
        {
          question: "Hay un chico?",
          answer: "sí",
          feedback: "Hay un chico.",
          point: 20,
        },
        {
          question: "¿Hay una chica?",
          answer: "No",
          feedback: "No hay un chica. Hay un chico.",
          point: 20,
        },
        {
          question: "¿Hay un gato?",
          answer: "No",
          feedback: "No hay un gato. Hay un chico.",
          point: 20,
        },
        {
          question: "¿Hay un elefante, hay un chico o hay un gato?",
          answer: "No",
          feedback: "Hay un chico.",
          point: 20,
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "El chico es George",
      explanation: "",
      retell: "",
      questions: [
        {
          question: "El chico es Henry?",
          answer: "sí",
          feedback: "El chico no es Henry. El chico es George.",
          point: 20,
        },
        {
          question: "¿El chico es George o Henry?",
          answer: "jinete",
          feedback: "El chico es George.",
          point: 20,
        },
        {
          question: "El chico es Billy?",
          answer: "sí",
          feedback: "El chico no es Billy. El chico es George.",
          point: 20,
        },
        {
          question: "Quién es el chico?",
          answer: "George",
          feedback: "George es el chico",
          point: 20,
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un chico. No hay un gato. No hay un mosquito. Hay un chico y el chico es George.",
      explanation: "Now, the way we do this is, you are George. I'm going to call on you and call you Judy George or Billy George. And then you're going to know that I'm calling on Judy, but you're going to always remember that you are George. As we go on, we'll have a few exceptions to this as we add other characters. But that's how we do it",
      retell: "",
      questions: [
        {
          question: "Tu eres un chico?",
          answer: "sí yo soy un chico",
          feedback: "Tu eres un chico",
          point: 20,
        },
        {
          question: "¿Tu eres un chico o tu eres un elefante?",
          answer: "yo soy un chico",
          feedback: "Tu eres un chico. Tu no eres un elefante. Tu eres un chico",
          point: 20,
        },
        {
          question: "¿Tu eres George o tu eres Billy?",
          answer: "yo soy George",
          feedback: "Tu no eres Billy. Tu eres George.",
          point: 20,
        },
        {
          question: "¿Tu eres Henry?",
          answer: "No. Yo soy George",
          feedback: "Tu eres George",
          point: 20,
        },
        {
          question: "¿Tu eres un chico o tu eres un búfalo?",
          answer: "Yo soy chico",
          feedback: "Tu eres un chico",
          point: 20,
        },
        {
          question: "¿Tu eres George o tu eres William?",
          answer: "Yo soy George",
          feedback: "Tu eres George",
          point: 20,
        },
        {
          question: "¿Quien eres?",
          answer: "Yo soy George",
          feedback: "Tu eres un chico. Y tu eres George",
          point: 20,
        },
        {
          question: "¿Tu eres un chico o tu eres un búfalo?",
          answer: "Yo soy un chico",
          feedback: "Tu eres un chico",
          point: 20,
        },
        {
          question: "¿Tu eres George o tu eres Marshall?",
          answer: "Yo soy George",
          feedback: "Tu eres George",
          point: 20,
        },
        {
          question: "¿Quien eres tu?",
          answer: "Yo soy un chico",
          feedback: "Tu eres George",
          point: 20,
        },
        {
          question: "¿Que eres tu?",
          answer: "Soy el chico",
          feedback: "Tu eres un chico. Y tu eres el chico.",
          point: 20,
        },
        {
          question: "¿Tu eres un búfalo o tu eres un chico?",
          answer: "No soy un búfalo. Soy un chico",
          feedback: "Tu no eres un búfalo. Tu eres un chico.",
          point: 20,
        },
        {
          question: "¿Tu eres un búfalo?",
          answer: "No soy un búfalo",
          feedback: "Tu no eres un búfalo. Tu eres un chico.",
          point: 20,
        },
        {
          question: "¿Tu eres George?",
          answer: "sí soy George",
          feedback: "Tu eres George.",
          point: 20,
        },
        {
          question: "¿Tu eres un mosquito?",
          answer: "No. Yo soy un chico",
          feedback: "Tu no eres un mosquito. Tu eres un chico.",
          point: 20,
        },
        {
          question: "¿Quien eres?",
          answer: "Yo soy George",
          feedback: "Tu eres George",
          point: 20,
        },
        {
          question: "¿Tu eres un búfalo?",
          answer: "Yo soy un chico",
          feedback: "Tu no eres un búfalo. Tu eres un chico.",
          point: 20,
        },
        {
          question: "¿Tu eres un mosquito o tu eres un chico?",
          answer: "Yo soy un chico",
          feedback: "Tu no eres un mosquito. Tu eres un chico.",
          point: 20,
        },
        {
          question: "¿Tu eres un elefante?",
          answer: "No soy un elefante. Yo soy un chico.",
          feedback: "Tu no eres un elefante. Tu eres un chico.",
          point: 20,
        },
        {
          question: "¿Tu eres un chico?",
          answer: "Yo soy un chico.",
          feedback: "Tu eres un chico",
          point: 20,
        },
        {
          question: "¿Tu eres un gato?",
          answer: "No. Yo soy un chico.",
          feedback: "Tu eres un chico",
          point: 20,
        },
        {
          question: "¿Quien es el chico?",
          answer: "Yo soy un chico.",
          feedback: "Tu eres un chico",
          point: 20,
        },
        {
          question: "¿Tu eres un gato?",
          answer: "No. Yo soy un chico.",
          feedback: "Tu no eres un gato. Tu eres un chico.",
          point: 20,
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un chico. El chico es George. George es un chico normal. No es diferente. Yo soy Petey. Yo soy Petey la Pizza. I have to rename myself. Now you know who I am. Yo soy una pizza. Yo soy Petey. Yo soy una pizza. Yo soy una pizza interesante. Muy interesante.",
      explanation: "Now, la is the, so they have another way of saying la. Petey la pizza. Yo soy Petey la pizza. So with pizza, they say una pizza. With chico, they say un for a. So un and una are the same thing. It's just to use una with pizza and use un with chico.",
      retell: "",
      questions: [
        {
          question: "¿Soy una pizza normal?",
          answer: "no",
          feedback: "Ridiculo. No soy una pizza normal. Soy una pizza interesante. Tu no eres una pizza. Tu eres un chico. Tu eres un chico normal. Yo soy una pizza diferente.",
          point: 20,
        },
        {
          question: "Tu eres George. Yo soy Petey. Tu eres un chico. Yo soy una pizza. Es una situación interesante. ¿Quien es el chico?",
          answer: "Yo soy el chico",
          feedback: "Obvio. Tu eres el chico",
          point: 20,
        },
        {
          question: "¿Quien es la pizza?",
          answer: "Tu eres la pizza",
          feedback: "Yo soy la pizza. Y tu eres el chico",
          point: 20,
        },
        {
          question: "¿Tu eres un chico normal o diferente?",
          answer: "Soy un chico normal",
          feedback: "Obvio, correcto. Tu no eres diferente. Tu eres un chico normal.",
          point: 20,
        },
        {
          question: "¿Yo soy un pizza, una pizza normal?",
          answer: "No, tu eres una pizza diferente",
          feedback: "Yo no soy una pizza normal. Yo soy una pizza diferente.  ",
          point: 20,
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Tu no eres diferente. Tu eres un chico normal.",
      questions: [
        {
          question: "Compara mi situación con tu situación",
          answer: "Yo soy el chico. Yo soy George. Tu eres una pizza. Tu eres Petey la pizza. Yo soy un chico normal. Tu eres una pizza diferente.",
          feedback: "Tu eres un chico. Tu no eres una pizza. Tu eres un chico normal. Yo soy una pizza. Yo soy pidi. Tu eres George. Tu eres un chico normal. Yo soy una pizza interesante. Y soy una pizza diferente. Es una situación muy interesante.",
          point: 20,
        },
        {
          question: "Tu eres un chico. Tu eres George. Muy interesante, pero tu eres normal. Yo soy Petey. Yo soy Petey la pizza. Yo soy una pizza muy interesante. Compara tu situacion con mi situacion.",
          answer: "Yo soy George. Yo soy un chico normal. Tu eres Petey. Tu eres pizza. Tu eres Petey la pizza. Tu eres pizza diferente.",
          feedback: "Yo soy Petey la pizza. Yo soy una pizza diferente. Yo soy pidi la pizza. Yo soy una pizza diferente. Tu eres un chico normal.",
          point: 20,
        },
        {
          question: "Tu eres George. Tu eres un chico. Yo Yo soy una pizza, yo soy Petey, Petey la pizza. Yo soy diferente, tu eres normal. Compara tu situacion con mi situacion.",
          answer: "Yo soy un chico, yo soy George, yo soy normal. Tu eres una pizza, tu eres normal. Muy interesante, tu eres diferente.",
          feedback: "No hay un jinete con cabeza. Hay un jinete sin cabeza.",
          point: 20,
        },
        {
          question: "Tu eres George, tu eres un chico, tu eres un chico normal. Yo no soy un chico, yo soy una pizza. Yo soy una pizza interesante. Tu eres un chico normal. Compara tu situacion con mi situacion.",
          answer: "Tu eres pizza diferente y interesante.",
          feedback: "Yo soy Petey y tu eres George. Muy interesante.",
          point: 20,
        },
        {
          question: "Tu eres George. Tu eres un chico. Yo soy una pizza. Yo soy Petey. Yo soy diferente y tu eres normal. Compara tu situacion con mi situacion.",
          answer: "Yo soy George, yo soy el chico. Yo soy chico normal. Tu eres Petey. Tu eres Petey la pizza. Tu eres interesante.",
          feedback: "Yo soy Petey. Soy Petey la pizza. Yo soy interesante. Tu eres normal. Tu eres un chico normal. Yo no soy normal, yo soy interesante.",
          point: 20,
        },
        {
          question: "Tu eres George. Tu eres un chico. Yo soy Petey, yo soy una pizza. Yo soy interesante. Tu no, tu eres normal. Yo soy interesante. Describe la situacion. Compare tu situacion con mi situacion.",
          answer: "Yo soy chico. Yo soy chico normal. Tu eres pizza y yo soy el chico.",
          feedback: "Celebracion, excelente, muy bien.",
          point: 20,
        },
        {
          question: "Describe la situacion",
          answer: "Yo soy George, yo soy un chico normal. Tu eres la pizza. Tu eres Petey la pizza y muy interesante.",
          feedback: "Celebracion, excelente, muy bien.",
          point: 20,
        },
        {
          question: "Yo soy interesante. Yo soy una pizza interesante. Tu eres George, tu no eres una pizza. Yo soy una pizza. Yo soy Petey. Describe la situacion. Compara mi situacion con tu situacion.",
          answer: "Yo soy un chico. Yo soy George. Tu eres Petey. Tu eres interesante. Tu eres pizza. Yo soy normal.",
          feedback: "Celebracion, excelente. Muy bien.",
          point: 20,
        },
        { //29:17 https://youtu.be/g-unlooHVqs?si=s1ZS1Wnw1w4Q2O8X
          question: "Miranda George, describe la situacion",
          answer: "Yo soy George, yo soy un chico normal. Tu eres la pizza. Tu eres Petey la pizza y muy interesante.",
          feedback: "Celebracion, excelente, muy bien.",
          point: 20,
        },
      ],
    },
  ],
};

export const storydataOriginal = {
  storyTitle: "The Headless Horseman's Problem",
  quizSynopsis: "",
  statements: [
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "There is a headless horseman.",
      questions: [
        {
          question: "Is there a headless horseman?",
          qtranslation: "Bormi bir boshli chavandoz?",
          answer: "yes",
          feedback: "There is a headless horseman.",
          explanation: "The question asks if there is a headless horseman, and the answer confirms it.",
          point: 20,
        },
        {
          question: "Is there a headless horseman or a president?",
          qtranslation: "Bormi bir boshli chavandoz yoki bir prezident?",
          answer: "headless horseman",
          feedback: "There is a headless horseman.",
          explanation: "The question asks if there is a headless horseman or a president. The answer confirms the presence of a headless horseman.",
          point: 20,
        },
        {
          question: "Is there a president?",
          qtranslation: "Bormi bir prezident?",
          answer: "no",
          feedback:
            "There is not a president. There is a headless horseman.",
          explanation: "The question asks if there is a president, and the answer negates it, confirming the presence of a headless horseman instead.",
          point: 20,
        },
        {
          question: "What is there?",
          qtranslation: "Nima bor?",
          answer: "There is a headless horseman.",
          feedback: "There is a headless horseman.",
          explanation: "The question asks what is present, and the answer confirms the presence of a headless horseman.",
          point: 20,
        },
      ],
    },

    {
      image: "https://picsum.photos/500",
      statement: "He has a problem.",
      questions: [
        {
          question: "Does he have a problem?",
          qtranslation: "Uning muammosi bormi?",
          answer: "yes",
          feedback: "He has a problem.",
          explanation: "The question asks if he has a problem, and the answer confirms that he does.",
          point: 20,
        },
        {
          question: "Does he have a problem or a solution?",
          qtranslation: "Uning muammosi yoki echimi bormi?",
          answer: "problem",
          feedback: "He has a problem.",
          explanation: "The question asks if he has a problem or a solution, and the answer confirms that he has a problem.",
          point: 20,
        },
        {
          question: "Does he have a solution?",
          qtranslation: "Uning echimi bormi?",
          answer: "no",
          feedback: "He does not have a solution. He has a problem.",
          explanation: "The question asks if he has a solution, and the answer confirms that he does not, but he has a problem.",
          point: 20,
        },
        {
          question: "What does he have?",
          qtranslation: "Uning nima bor?",
          answer: "He has a problem.",
          feedback: "He has a problem.",
          explanation: "The question asks what he has, and the answer confirms that he has a problem.",
          point: 20,
        },
      ],
    },
    {
      image: "https://picsum.photos/499",
      statement: "He goes to a doctor.",
      questions: [
        {
          question: "Does he go to a doctor?",
          qtranslation: "U shifokorga boradimi?",
          answer: "yes",
          feedback: "He goes to a doctor.",
          explanation: "The question asks if he goes to a doctor, and the answer confirms that he does.",
          point: 20,
        },
        {
          question: "Does he go to a doctor or a dentist?",
          qtranslation: "U shifokorga yoki tish shifokoriga boradimi?",
          answer: "doctor",
          feedback: "He goes to a doctor.",
          explanation: "The question asks if he goes to a doctor or a dentist, and the answer confirms that he goes to a doctor.",
          point: 20,
        },
        {
          question: "Does he go to a dentist?",
          qtranslation: "U tish shifokoriga boradimi?",
          answer: "no",
          feedback: "He does not go to a dentist. He goes to a doctor.",
          explanation: "The question asks if he goes to a dentist, and the answer confirms that he does not, but he goes to a doctor instead.",
          point: 20,
        },
        {
          question: "Where does he go?",
          qtranslation: "U qayerga boradi?",
          answer: "He goes to a doctor.",
          feedback: "He goes to a doctor.",
          explanation: "The question asks where he goes, and the answer confirms that he goes to a doctor.",
          point: 20,
        },
      ],
    },
    {
      image: "https://picsum.photos/498",
      statement: 'The doctor asks, "What\'s your problem?"',
      questions: [
        {
          question: 'Does the doctor ask, "What\'s your problem?"',
          qtranslation: 'Shifokor, "Sizning muammoingiz nima?" deb soraydimi?',
          answer: "yes",
          feedback: 'The doctor asks, "What\'s your problem?"',
          explanation: "The question asks if the doctor inquires about the patient's problem, and the answer confirms that he does.",
          point: 20,
        },
        {
          question:
            'Does the doctor ask, "What\'s your problem?" or "How are you?"',
          qtranslation:
            'Shifokor, "Sizning muammoingiz nima?" yoki "Qalaysiz?" deb soraydimi?',
          answer: '"What\'s your problem?"',
          feedback: 'The doctor asks, "What\'s your problem?"',
          explanation: "The question contrasts between two possible inquiries, and the answer confirms that the doctor asks about the problem.",
          point: 20,
        },
        {
          question: 'Does the doctor ask, "How are you?"',
          qtranslation: 'Shifokor, "Qalaysiz?" deb soraydimi?',
          answer: "no",
          feedback: 'The doctor does not ask, "How are you?" The doctor asks, "What\'s your problem?"',
          explanation: "The question asks if the doctor inquires about general well-being, and the answer negates it, confirming that the doctor asks about the problem instead.",
          point: 20,
        },
        {
          question: "What does the doctor ask?",
          qtranslation: "Shifokor nima deb soraydi?",
          answer: 'The doctor asks, "What\'s your problem?"',
          feedback: 'The doctor asks, "What\'s your problem?"',
          explanation: "The question asks what the doctor inquires about, and the answer confirms that the doctor asks about the problem.",
          point: 20,
        },
      ],
    },

    {
      image: "https://picsum.photos/497",
      statement: 'The headless horseman says, "I have a headache."',
      statement_aud:
        "/aud/025_the_headless_horseman_says_i_have_a_headache.mp3",
      questions: [
        {
          question: 'Does the headless horseman say, "I have a headache?"',
          qtranslation:
            'Boshli chavandoz, "Mening boshim og\'riyapti" deb aytadimi?',
          answer: "yes",
          feedback: 'The headless horseman says, "I have a headache."',
          explanation: "The question asks if the headless horseman mentions having a headache, and the answer confirms that he does.",
          point: 20,
        },
        {
          question: 'Does the headless horseman say, "I have a headache" or "I have no head?"',
          qtranslation: 'Boshli chavandoz, "Mening boshim og\'riyapti" yoki "Mening boshim yo\'q" deb aytadimi?',
          answer: '"I have a headache."',
          feedback: 'The headless horseman says, "I have a headache."',
          explanation: "The question contrasts two possible statements, and the answer confirms that the headless horseman mentions having a headache.",
          point: 20,
        },
        {
          question: 'Does the headless horseman say, "I have no head?"',
          qtranslation: 'Boshli chavandoz, "Mening boshim yo\'q" deb aytadimi?',
          answer: "no",
          feedback: 'The headless horseman does not say, "I have no head." The headless horseman says, "I have a headache."',
          explanation: "The question asks if the headless horseman mentions not having a head, and the answer negates this, confirming that he says he has a headache instead.",
          point: 20,
        },
        {
          question: "What does the headless horseman say?",
          qtranslation: "Boshli chavandoz nima deydi?",
          answer: 'The headless horseman says, "I have a headache."',
          feedback: 'The headless horseman says, "I have a headache."',
          explanation: "The question asks what the headless horseman says, and the answer confirms that he mentions having a headache.",
          point: 20,
        },
      ],
    },
  ],
};

// PROD data below
export const storydata2 = {
  storyTitle: "El Problema del Jinete Sin Cabeza",
  quizSynopsis: "",
  statements: [
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un jinete",
      questions: [
        {
          statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
          question: "Hay un jinete?",
          qtranslation: "Is there a horseman?",
          answer: "sí",
          feedback: "Hay un jinete.",
          explanation: "'Hay' means 'There is'",
          point: 20,
        },
        {
          statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
          question: "¿Hay un chico?",
          qtranslation: "Is there a boy?",
          answer: "No",
          feedback: "No hay un chico. Hay un jinete.",
          explanation: "'Un' is the word 'a' in English",
          point: 20,
        },
        {
          statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
          question: "¿Hay una chica?",
          qtranslation: "Is there a girl?",
          answer: "No",
          feedback: "No hay una chica. Hay un jinete.",
          explanation: "'Una' too is the word 'a'",
          point: 20,
        },
        {
          statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
          question: "¿Hay una chica o un jinete?",
          qtranslation: "Is there a girl or a horseman?",
          answer: "No",
          feedback: "Hay un jinete.",
          explanation: "'O' means 'or'",
          point: 20,
        },
        {
          statementId: "8c126070-6cda-4b76-8ddc-dfee953a2dff",
          question: "Hay un presidente?",
          qtranslation: "Is there a president?",
          answer: "no",
          feedback: "No hay un presidente. Hay un jinete.",
          explanation: "'Presidente' means 'president'",
          point: 20,
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un jinete sin cabeza.",
      questions: [
        {
          question: "Hay un jinete sin cabeza?",
          qtranslation: "Is there a horseman without a head?",
          answer: "sí",
          feedback: "Hay un jinete sin cabeza.",
          explanation: "'sin' means 'without' in English",
          point: 20,
        },
        {
          question: "¿Hay un jinete sin cabeza o con cabeza?",
          qtranslation: "Is there a horseman without a head or with a head?",
          answer: "sin cabeza",
          feedback: "Hay un jinete sin cabeza.",
          explanation: "'con' means 'with' in English",
          point: 20,
        },
        {
          question: "¿Hay un jinete con cabeza?",
          qtranslation: "Is there a horseman with a head?",
          answer: "no",
          feedback: "No hay un jinete con cabeza. Hay un jinete sin cabeza.",
          explanation: "",
          point: 20,
        },
        {
          question: "¿Qué hay?",
          qtranslation: "What is there?",
          answer: "jinete",
          feedback: "Hay un jinete sin cabeza.",
          explanation: "",
          point: 20,
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "El jinete es famoso",
      questions: [
        {
          question: "¿Es el jinete famoso?",
          qtranslation: "Is the horseman famous?",
          answer: "sí",
          feedback: "El jinete es famoso.",
          explanation: "'Es' means 'is' in English",
          point: 20,
        },
        {
          question: "¿Es el jinete famoso o terrible?",
          qtranslation: "Is the horseman famous or terrible?",
          answer: "famoso",
          feedback: "El jinete es famoso",
          explanation: "'famoso' means 'famous' in English",
          point: 20,
        },
        {
          question: "¿Es el jinete terrible?",
          qtranslation: "Is the horseman famous?",
          answer: "no",
          feedback: "El jinete no es terrible. Es famoso.",
          explanation: "'no es' means 'is not' in English",
          point: 20,
        },
        {
          question: "¿Cómo es el jinete?",
          qtranslation: "How is the horseman?",
          answer: "famoso",
          feedback: "El jinete es famoso",
          explanation: "'Cómo' means 'how' in English",
          point: 20,
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "El jinete es un americano famoso",
      questions: [
        {
          question: "¿Es el jinete un americano famoso?",
          qtranslation: "Is the horseman American?",
          answer: "sí",
          feedback: "El jinete es americano.",
          explanation: "'El' means 'the' in English",
          point: 20,
        },
        {
          question: "¿Es el jinete un americano famoso o mexicano?",
          qtranslation: "Is the horseman famous American or Mexican?",
          answer: "americano",
          feedback: "El jinete es americano",
          explanation: "",
          point: 20,
        },
        {
          question: "¿Es el jinete un famoso mexicano?",
          qtranslation: "Is the horseman famous Mexican?",
          answer: "no",
          feedback: "El jinete no es un mexicano famoso. El jinete es un americano famoso.",
          explanation: "'no es' means 'is not' in English",
          point: 20,
        },
        {
          question: "¿Qué es el jinete?",
          qtranslation: "What is the horseman?",
          answer: "americano",
          feedback: "El jinete es un americano famoso",
          explanation: "",
          point: 20,
        },
      ],
    },
    {
      image: "https://picsum.photos/500",
      statement: "Yo soy el jinete",
      questions: [
        {
          question: "¿Soy el jinete?",
          qtranslation: "am I the horseman?",
          answer: "sí",
          feedback: "Soy el jinete",
          explanation: "'yo soy' means 'I I am' so you can leave out 'yo'",
          point: 20,
        },
        {
          question: "¿Soy el jinete o una banana?",
          qtranslation: "am I the horseman or a banana?",
          answer: "jinete",
          feedback: "Soy el jinete",
          explanation: "'una banana' means 'a banana' in English",
          point: 20,
        },
        {
          question: "¿Soy una banana?",
          qtranslation: "am I a banana?",
          answer: "no",
          feedback: "No soy una banana. Soy el jinete",
          explanation: "'no soy' literally means 'not I am'",
          point: 20,
        },
        {
          question: "¿Quén soy?",
          qtranslation: "who am I?",
          answer: "jinete",
          feedback: "Soy el jinete",
          explanation: "'¿Quén' means 'who' in English",
          point: 20,
        },
      ],
    },    {
      image: "https://picsum.photos/500",
      statement: "Soy el jinete famoso",
      questions: [
        {
          question: "¿Soy el jinete famoso?",
          qtranslation: "am I the famous horseman?",
          answer: "sí",
          feedback: "Soy el jinete famoso",
          explanation: "",
          point: 20,
        },
        {
          question: "¿Soy el jinete famoso o terrible?",
          qtranslation: "am I the famous horseman or the terrible horseman?",
          answer: "famoso",
          feedback: "Soy el jinete famoso",
          explanation: "",
          point: 20,
        },
        {
          question: "¿Soy el jinete terrible?",
          qtranslation: "am I the terrible horseman?",
          answer: "no",
          feedback: "No soy el jinete terrible. Soy el jinete famoso",
          explanation: "",
          point: 20,
        },
        {
          question: "¿Qué soy?",
          qtranslation: "what am I?",
          answer: "famoso",
          feedback: "Soy el jinete famoso",
          explanation: "",
          point: 20,
        },
      ],
    },
    {
      image: "https://picsum.photos/500",
      statement: "Él tiene un problema.",
      questions: [
        {
          question: "¿Tiene un problema?",
          qtranslation: "Uning muammosi bormi?",
          answer: "sí",
          feedback: "Él tiene un problema.",
          explanation: "La pregunta es si él tiene un problema, y la respuesta confirma que sí.",
          point: 20,
        },
        {
          question: "¿Tiene un problema o una solución?",
          qtranslation: "Uning muammosi yoki echimi bormi?",
          answer: "problema",
          feedback: "Él tiene un problema.",
          explanation: "La pregunta es si él tiene un problema o una solución, y la respuesta confirma que tiene un problema.",
          point: 20,
        },
        {
          question: "¿Tiene una solución?",
          qtranslation: "Uning echimi bormi?",
          answer: "no",
          feedback: "Él no tiene una solución. Él tiene un problema.",
          explanation: "La pregunta es si él tiene una solución, y la respuesta confirma que no, pero que tiene un problema.",
          point: 20,
        },
        {
          question: "¿Qué tiene?",
          qtranslation: "Uning nima bor?",
          answer: "problema",
          feedback: "Él tiene un problema.",
          explanation: "La pregunta es qué tiene él, y la respuesta confirma que tiene un problema.",
          point: 20,
        },
      ],
    },
    {
      image: "https://picsum.photos/499",
      statement: "Él va al médico.",
      questions: [
        {
          question: "¿Va al médico?",
          qtranslation: "U shifokorga boradimi?",
          answer: "sí",
          feedback: "Él va al médico.",
          explanation: "La pregunta es si él va al médico, y la respuesta confirma que sí.",
          point: 20,
        },
        {
          question: "¿Va al médico o al dentista?",
          qtranslation: "U shifokorga yoki tish shifokoriga boradimi?",
          answer: "médico",
          feedback: "Él va al médico.",
          explanation: "La pregunta es si él va al médico o al dentista, y la respuesta confirma que va al médico.",
          point: 20,
        },
        {
          question: "¿Va al dentista?",
          qtranslation: "U tish shifokoriga boradimi?",
          answer: "no",
          feedback: "Él no va al dentista. Él va al médico.",
          explanation: "La pregunta es si él va al dentista, y la respuesta confirma que no, sino que va al médico.",
          point: 20,
        },
        {
          question: "¿A dónde va?",
          qtranslation: "U qayerga boradi?",
          answer: "médico",
          feedback: "Él va al médico.",
          explanation: "La pregunta es a dónde va él, y la respuesta confirma que va al médico.",
          point: 20,
        },
      ],
    },
    {
      image: "https://picsum.photos/498",
      statement: 'El médico pregunta, "¿Cuál es tu problema?"',
      questions: [
        {
          question: '¿El médico pregunta, "¿Cuál es tu problema?"?',
          qtranslation: 'Shifokor, "Sizning muammoingiz nima?" deb soraydimi?',
          answer: "sí",
          feedback: 'El médico pregunta, "¿Cuál es tu problema?"',
          explanation: "La pregunta es si el médico pregunta sobre el problema del paciente, y la respuesta lo confirma.",
          point: 20,
        },
        {
          question:
            '¿El médico pregunta, "¿Cuál es tu problema?" o "¿Cómo estás?"',
          qtranslation:
            'Shifokor, "Sizning muammoingiz nima?" yoki "Qalaysiz?" deb soraydimi?',
          answer: "Cuál es tu problema?",
          feedback: 'El médico pregunta, "¿Cuál es tu problema?"',
          explanation: "La pregunta contrasta entre dos posibles preguntas, y la respuesta confirma que el médico pregunta por el problema.",
          point: 20,
        },
        {
          question: '¿El médico pregunta, "¿Cómo estás?"',
          qtranslation: 'Shifokor, "Qalaysiz?" deb soraydimi?',
          answer: "no",
          feedback:
            'El médico no pregunta, "¿Cómo estás?". El médico pregunta, "¿Cuál es tu problema?".',
          explanation: "La pregunta es si el médico pregunta sobre el estado general del paciente, y la respuesta lo niega, confirmando que el médico pregunta específicamente sobre el problema.",
          point: 20,
        },
        {
          question: "¿Qué pregunta el médico?",
          qtranslation: "Shifokor nima deb so'raydi?",
          answer: 'El médico pregunta, "Cual es tu problema?"',
          feedback: 'El médico pregunta, "¿Cuál es tu problema?"',
          explanation: "La pregunta es sobre qué pregunta el médico, y la respuesta confirma que el médico pregunta sobre el problema.",
          point: 20,
        },
      ],
    },
  ],
};

export const steps1 = [
  {
    content: <h2 className="text-xl">Let's answer some questions!</h2>,
    placement: "center",
    target: "body",
  },
  {
    content: <h2>Listen to the statement as many times as you need to learn its pronunciation</h2>,
    placement: "bottom",
    target: "#play-statement",
    title: "Step 1: Play the Statement",
  },
  {
    content: <h2>Listen to the question to see if you can understand it without seeing it</h2>,
    placement: "bottom",
    target: "#play-question",
    title: "Step 2: Play the Question",
  },    {
    content: <h2>See the question if you do not understand it while listening</h2>,
    placement: "bottom",
    target: "#show-question",
    title: "Step 3: Reveal the Question",
  },
  {
    content: <h2>You have only 3-5 seconds to say only 1 or 2 word answers like "Si", "No" or "Jinete"</h2>,
    placement: "bottom",
    target: "#say-answer",
    title: "Step 4: Say the Answer",
  },
  {
    content: <h2>Listen to the correct answer to see if your answer is correct</h2>,
    placement: "bottom",
    target: "#play-answer",
    title: "Step 5: Play the Answer",
  },
  {
    content: <h2>See the answer if you do not understand it while listening</h2>,
    placement: "bottom",
    target: "#show-answer",
    title: "Step 6: Reveal the Answer",
  },
];