import { v4 as uuid } from 'uuid'
console.log(uuid())

export const story1Statements = [
  {
    id: 1,
    image: "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
    statement: "Hay un jinete",
  },
  {
    id: 2,
    image: "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
    statement: "Hay un jinete sin cabeza",
  },
];

export const story1Questions = [
  {
    id: 1,
    statementId: 1,
    question: "Hay un jinete?",
    image:"",
    translation: "Is there a horseman?",
    answer: "sí",
    message: "Hay un jinete.",
    explanation: "This is the question and 'Hay' means 'There is'",
    point: 20,
  },
  {
    id: 2,
    statementId: 1,
    question: "¿Hay un chico?",
    image:"",
    translation: "Is there a boy?",
    answer: "No",
    message: "No hay un chico. Hay un jinete.",
    explanation: "'Un' is the word 'a' in English",
    point: 20,
  },
  {
    id: 3,
    statementId: 2,
    question: "¿Hay una chica?",
    image:"",
    translation: "Is there a girl?",
    answer: "No",
    message: "No hay una chica. Hay un jinete.",
    explanation: "'Una' too is the word 'a'",
    point: 20,
  },
  {
    id: 4,
    statementId: 2,
    question: "¿Hay una chica o un jinete?",
    image:"",
    translation: "Is there a girl or a horseman?",
    answer: "No",
    message: "Hay un jinete.",
    explanation: "'O' means 'or'",
    point: 20,
  },
  {
    id: 5,
    statementId: 2,
    question: "Hay un presidente?",
    image:"",
    translation: "Bormi bir prezident?",
    answer: "no",
    message: "No hay un presidente. Hay un jinete.",
    explanation: "'Presidente' means 'president'",
    point: 20,
  },
]

export const storydataTestJinete = {
  quizTitle: "El Problema del Jinete Sin Cabeza",
  quizSynopsis: "",
  statements: [
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un jinete",
      questions: [
        {
          question: "Hay un jinete?",
          translation: "Bormi bir boshli chavandoz?",
          answer: "sí",
          messageForAnswer: "Hay un jinete.",
          explanation: "'Hay' means 'There is'",
          point: "20",
        },
        {
          question: "¿Hay un chico?",
          translation: "Bormi bir bola?",
          answer: "No",
          messageForAnswer: "No hay un chico. Hay un jinete.",
          explanation: "'Un' is the word 'a' in English",
          point: "20",
        },
        {
          question: "¿Hay una chica?",
          translation: "Bormi bir boshli chavandoz yoki bir prezident?",
          answer: "No",
          messageForAnswer: "No hay una chica. Hay un jinete.",
          explanation: "'Una' too is the word 'a'",
          point: "20",
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un jinete sin cabeza.",
      questions: [
        {
          question: "Hay un jinete sin cabeza?",
          translation: "Bormi bir boshli chavandoz?",
          answer: "sí",
          messageForAnswer: "Hay un jinete sin cabeza.",
          explanation: "La pregunta es si hay un jinete sin cabeza, y la respuesta lo confirma.",
          point: "20",
        },
        {
          question: "¿Hay un jinete sin cabeza o un banana?",
          translation: "Bormi bir boshli chavandoz yoki bir banan?",
          answer: "jinete",
          messageForAnswer: "Hay un jinete sin cabeza.",
          explanation: "La pregunta es si hay un jinete sin cabeza o un banana. La respuesta confirma la presencia de un jinete sin cabeza.",
          point: "20",
        },
      ],
    },
  ],
};

export const storydataTestChico = {
  quizTitle: "El Problema del Chico",
  quizSynopsis: "",
  statements: [
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un chico",
      questions: [
        {
          question: "Hay un chico?",
          translation: "Is there a boy?",
          answer: "sí",
          messageForAnswer: "Hay un chico.",
          explanation: "'Hay' means 'There is'",
          point: "20",
        },
        {
          question: "¿Hay una chica?",
          translation: "Is there a girl?",
          answer: "No",
          messageForAnswer: "No hay un chica. Hay un chico.",
          explanation: "'Una' is the word 'a' in English",
          point: "20",
        },
        {
          question: "¿Hay un gato?",
          translation: "Is there a cat?",
          answer: "No",
          messageForAnswer: "No hay un gato. Hay un chico.",
          explanation: "'gato' sounds like cat",
          point: "20",
        },
        {
          question: "¿Hay un elefante, hay un chico o hay un gato?",
          translation: "Bormi bir boshli chavandoz yoki bir prezident?",
          answer: "No",
          messageForAnswer: "Hay un chico.",
          explanation: "'Un' too is the word 'a'",
          point: "20",
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "El chico es Paco",
      questions: [
        {
          question: "El chico es Pepe?",
          translation: "Is the boy Pepe?",
          answer: "sí",
          messageForAnswer: "El chico no es Pepe. El chico es Paco.",
          explanation: "",
          point: "20",
        },
        {
          question: "¿El chico es Paco o Pepe?",
          translation: "Is the boy Paco or Pepe?",
          answer: "jinete",
          messageForAnswer: "El chico es Paco.",
          explanation: "",
          point: "20",
        },
        {
          question: "El chico es Billy?",
          translation: "Is the boy Billy?",
          answer: "sí",
          messageForAnswer: "El chico no es Billy. El chico es Paco.",
          explanation: "",
          point: "20",
        },
        {
          question: "Quién es el chico?",
          translation: "Who is the boy?",
          answer: "Paco",
          messageForAnswer: "Paco es el chico",
          explanation: "",
          point: "20",
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un chico. No hay un gato. No hay un mosquito. Hay un chico y el chico es Paco.",
      questions: [
        {
          question: "El chico es Pepe?",
          translation: "Is the boy Pepe?",
          answer: "sí",
          messageForAnswer: "El chico no es Pepe. El chico es Paco.",
          explanation: "Now, the way we do this is, you are Paco. I'm going to call on you and call you Judy Paco or Billy Paco. And then you're going to know that I'm calling on Judy, but you're going to always remember that you are George. As we go on, we'll have a few exceptions to this as we add other characters. But that's how we do it",
          point: "20",
        },
        {
          question: "¿El chico es Paco o Pepe?",
          translation: "Is the boy Paco or Pepe?",
          answer: "jinete",
          messageForAnswer: "El chico es Paco.",
          explanation: "",
          point: "20",
        },
        {
          question: "El chico es Billy?",
          translation: "Is the boy Billy?",
          answer: "sí",
          messageForAnswer: "El chico no es Billy. El chico es Paco.",
          explanation: "",
          point: "20",
        },
        {
          question: "Quién es el chico?",
          translation: "Who is the boy?",
          answer: "Paco",
          messageForAnswer: "Paco es el chico",
          explanation: "",
          point: "20",
        },
      ],
    },
  ],
};

export const storydata = {
  quizTitle: "El Problema del Jinete Sin Cabeza",
  quizSynopsis: "",
  statements: [
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un jinete",
      questions: [
        {
          question: "Hay un jinete?",
          translation: "Is there a horseman?",
          answer: "sí",
          messageForAnswer: "Hay un jinete.",
          explanation: "'Hay' means 'There is'",
          point: "20",
        },
        {
          question: "¿Hay un chico?",
          translation: "Is there a boy?",
          answer: "No",
          messageForAnswer: "No hay un chico. Hay un jinete.",
          explanation: "'Un' is the word 'a' in English",
          point: "20",
        },
        {
          question: "¿Hay una chica?",
          translation: "Is there a girl?",
          answer: "No",
          messageForAnswer: "No hay una chica. Hay un jinete.",
          explanation: "'Una' too is the word 'a'",
          point: "20",
        },
        {
          question: "¿Hay una chica o un jinete?",
          translation: "Is there a girl or a horseman?",
          answer: "No",
          messageForAnswer: "Hay un jinete.",
          explanation: "'O' means 'or'",
          point: "20",
        },
        {
          question: "Hay un presidente?",
          translation: "Is there a president?",
          answer: "no",
          messageForAnswer: "No hay un presidente. Hay un jinete.",
          explanation: "'Presidente' means 'president'",
          point: "20",
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "Hay un jinete sin cabeza.",
      questions: [
        {
          question: "Hay un jinete sin cabeza?",
          translation: "Is there a horseman without a head?",
          answer: "sí",
          messageForAnswer: "Hay un jinete sin cabeza.",
          explanation: "'sin' means 'without' in English",
          point: "20",
        },
        {
          question: "¿Hay un jinete sin cabeza o con cabeza?",
          translation: "Is there a horseman without a head or with a head?",
          answer: "sin cabeza",
          messageForAnswer: "Hay un jinete sin cabeza.",
          explanation: "'con' means 'with' in English",
          point: "20",
        },
        {
          question: "¿Hay un jinete con cabeza?",
          translation: "Is there a horseman with a head?",
          answer: "no",
          messageForAnswer: "No hay un jinete con cabeza. Hay un jinete sin cabeza.",
          explanation: null,
          point: "20",
        },
        {
          question: "¿Qué hay?",
          translation: "What is there?",
          answer: "jinete",
          messageForAnswer: "Hay un jinete sin cabeza.",
          explanation: null,
          point: "20",
        },
      ],
    },
    
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "El jinete es famoso",
      questions: [
        {
          question: "¿Es el jinete famoso?",
          translation: "Is the horseman famous?",
          answer: "sí",
          messageForAnswer: "El jinete es famoso.",
          explanation: "'Es' means 'is' in English",
          point: "20",
        },
        {
          question: "¿Es el jinete famoso o terrible?",
          translation: "Is the horseman famous or terrible?",
          answer: "famoso",
          messageForAnswer: "El jinete es famoso",
          explanation: "'famoso' means 'famous' in English",
          point: "20",
        },
        {
          question: "¿Es el jinete terrible?",
          translation: "Is the horseman famous?",
          answer: "no",
          messageForAnswer: "El jinete no es terrible. Es famoso.",
          explanation: "'no es' means 'is not' in English",
          point: "20",
        },
        {
          question: "¿Cómo es el jinete?",
          translation: "How is the horseman?",
          answer: "famoso",
          messageForAnswer: "El jinete es famoso",
          explanation: "'Cómo' means 'how' in English",
          point: "20",
        },
      ],
    },
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "El jinete es un americano famoso",
      questions: [
        {
          question: "¿Es el jinete un americano famoso?",
          translation: "Is the horseman American?",
          answer: "sí",
          messageForAnswer: "El jinete es americano.",
          explanation: "'El' means 'the' in English",
          point: "20",
        },
        {
          question: "¿Es el jinete un americano famoso o mexicano?",
          translation: "Is the horseman famous American or Mexican?",
          answer: "americano",
          messageForAnswer: "El jinete es americano",
          explanation: null,
          point: "20",
        },
        {
          question: "¿Es el jinete un famoso mexicano?",
          translation: "Is the horseman famous Mexican?",
          answer: "no",
          messageForAnswer: "El jinete no es un mexicano famoso. El jinete es un americano famoso.",
          explanation: "'no es' means 'is not' in English",
          point: "20",
        },
        {
          question: "¿Qué es el jinete?",
          translation: "What is the horseman?",
          answer: "americano",
          messageForAnswer: "El jinete es un americano famoso",
          explanation: null,
          point: "20",
        },
      ],
    },
    {
      image: "https://picsum.photos/500",
      statement: "Yo soy el jinete",
      questions: [
        {
          question: "¿Soy el jinete?",
          translation: "am I the horseman?",
          answer: "sí",
          messageForAnswer: "Soy el jinete",
          explanation: "'yo soy' means 'I I am' so you can leave out 'yo'",
          point: "20",
        },
        {
          question: "¿Soy el jinete o una banana?",
          translation: "am I the horseman or a banana?",
          answer: "jinete",
          messageForAnswer: "Soy el jinete",
          explanation: "'una banana' means 'a banana' in English",
          point: "20",
        },
        {
          question: "¿Soy una banana?",
          translation: "am I a banana?",
          answer: "no",
          messageForAnswer: "No soy una banana. Soy el jinete",
          explanation: "'no soy' literally means 'not I am'",
          point: "20",
        },
        {
          question: "¿Qué soy?",
          translation: "what am I?",
          answer: "jinete",
          messageForAnswer: "Soy el jinete",
          explanation: "'¿Qué' means 'what' in English",
          point: "20",
        },
      ],
    },    {
      image: "https://picsum.photos/500",
      statement: "Soy el jinete famoso",
      questions: [
        {
          question: "¿Soy el jinete famoso?",
          translation: "am I the famous horseman?",
          answer: "sí",
          messageForAnswer: "Soy el jinete famoso",
          explanation: null,
          point: "20",
        },
        {
          question: "¿Soy el jinete famoso o terrible?",
          translation: "am I the famous horseman or the terrible horseman?",
          answer: "famoso",
          messageForAnswer: "Soy el jinete famoso",
          explanation: null,
          point: "20",
        },
        {
          question: "¿Soy el jinete terrible?",
          translation: "am I the terrible horseman?",
          answer: "no",
          messageForAnswer: "No soy el jinete terrible. Soy el jinete famoso",
          explanation: null,
          point: "20",
        },
        {
          question: "¿Qué soy?",
          translation: "what am I?",
          answer: "famoso",
          messageForAnswer: "Soy el jinete famoso",
          explanation: null,
          point: "20",
        },
      ],
    },
    {
      image: "https://picsum.photos/500",
      statement: "Él tiene un problema.",
      questions: [
        {
          question: "¿Tiene un problema?",
          translation: "Uning muammosi bormi?",
          answer: "sí",
          messageForAnswer: "Él tiene un problema.",
          explanation: "La pregunta es si él tiene un problema, y la respuesta confirma que sí.",
          point: "20",
        },
        {
          question: "¿Tiene un problema o una solución?",
          translation: "Uning muammosi yoki echimi bormi?",
          answer: "problema",
          messageForAnswer: "Él tiene un problema.",
          explanation: "La pregunta es si él tiene un problema o una solución, y la respuesta confirma que tiene un problema.",
          point: "20",
        },
        {
          question: "¿Tiene una solución?",
          translation: "Uning echimi bormi?",
          answer: "no",
          messageForAnswer: "Él no tiene una solución. Él tiene un problema.",
          explanation: "La pregunta es si él tiene una solución, y la respuesta confirma que no, pero que tiene un problema.",
          point: "20",
        },
        {
          question: "¿Qué tiene?",
          translation: "Uning nima bor?",
          answer: "problema",
          messageForAnswer: "Él tiene un problema.",
          explanation: "La pregunta es qué tiene él, y la respuesta confirma que tiene un problema.",
          point: "20",
        },
      ],
    },
    {
      image: "https://picsum.photos/499",
      statement: "Él va al médico.",
      questions: [
        {
          question: "¿Va al médico?",
          translation: "U shifokorga boradimi?",
          answer: "sí",
          messageForAnswer: "Él va al médico.",
          explanation: "La pregunta es si él va al médico, y la respuesta confirma que sí.",
          point: "20",
        },
        {
          question: "¿Va al médico o al dentista?",
          translation: "U shifokorga yoki tish shifokoriga boradimi?",
          answer: "médico",
          messageForAnswer: "Él va al médico.",
          explanation: "La pregunta es si él va al médico o al dentista, y la respuesta confirma que va al médico.",
          point: "20",
        },
        {
          question: "¿Va al dentista?",
          translation: "U tish shifokoriga boradimi?",
          answer: "no",
          messageForAnswer: "Él no va al dentista. Él va al médico.",
          explanation: "La pregunta es si él va al dentista, y la respuesta confirma que no, sino que va al médico.",
          point: "20",
        },
        {
          question: "¿A dónde va?",
          translation: "U qayerga boradi?",
          answer: "médico",
          messageForAnswer: "Él va al médico.",
          explanation: "La pregunta es a dónde va él, y la respuesta confirma que va al médico.",
          point: "20",
        },
      ],
    },
    {
      image: "https://picsum.photos/498",
      statement: 'El médico pregunta, "¿Cuál es tu problema?"',
      questions: [
        {
          question: '¿El médico pregunta, "¿Cuál es tu problema?"?',
          translation: 'Shifokor, "Sizning muammoingiz nima?" deb so‘raydimi?',
          answer: "sí",
          messageForAnswer: 'El médico pregunta, "¿Cuál es tu problema?"',
          explanation: "La pregunta es si el médico pregunta sobre el problema del paciente, y la respuesta lo confirma.",
          point: "20",
        },
        {
          question:
            '¿El médico pregunta, "¿Cuál es tu problema?" o "¿Cómo estás?"',
          translation:
            'Shifokor, "Sizning muammoingiz nima?" yoki "Qalaysiz?" deb so‘raydimi?',
          answer: "Cuál es tu problema?",
          messageForAnswer: 'El médico pregunta, "¿Cuál es tu problema?"',
          explanation: "La pregunta contrasta entre dos posibles preguntas, y la respuesta confirma que el médico pregunta por el problema.",
          point: "20",
        },
        {
          question: '¿El médico pregunta, "¿Cómo estás?"',
          translation: 'Shifokor, "Qalaysiz?" deb so‘raydimi?',
          answer: "no",
          messageForAnswer:
            'El médico no pregunta, "¿Cómo estás?". El médico pregunta, "¿Cuál es tu problema?".',
          explanation: "La pregunta es si el médico pregunta sobre el estado general del paciente, y la respuesta lo niega, confirmando que el médico pregunta específicamente sobre el problema.",
          point: "20",
        },
        {
          question: "¿Qué pregunta el médico?",
          translation: "Shifokor nima deb so'raydi?",
          answer: 'El médico pregunta, "Cual es tu problema?"',
          messageForAnswer: 'El médico pregunta, "¿Cuál es tu problema?"',
          explanation: "La pregunta es sobre qué pregunta el médico, y la respuesta confirma que el médico pregunta sobre el problema.",
          point: "20",
        },
      ],
    },
  ],
};

export const storydataEng = {
  quizTitle: "The Headless Horseman's Problem",
  quizSynopsis: "",
  statements: [
    {
      image:
        "https://raw.githubusercontent.com/muhiddinjv/poc/main/src/assets/img/headless_horseman.jpg",
      statement: "There is a headless horseman.",
      questions: [
        {
          question: "Is there a headless horseman?",
          translation: "Bormi bir boshli chavandoz?",
          answer: "yes",
          messageForAnswer: "There is a headless horseman.",
          explanation: "The question asks if there is a headless horseman, and the answer confirms it.",
          point: "20",
        },
        {
          question: "Is there a headless horseman or a president?",
          translation: "Bormi bir boshli chavandoz yoki bir prezident?",
          answer: "headless horseman",
          messageForAnswer: "There is a headless horseman.",
          explanation: "The question asks if there is a headless horseman or a president. The answer confirms the presence of a headless horseman.",
          point: "20",
        },
        {
          question: "Is there a president?",
          translation: "Bormi bir prezident?",
          answer: "no",
          messageForAnswer:
            "There is not a president. There is a headless horseman.",
          explanation: "The question asks if there is a president, and the answer negates it, confirming the presence of a headless horseman instead.",
          point: "20",
        },
        {
          question: "What is there?",
          translation: "Nima bor?",
          answer: "There is a headless horseman.",
          messageForAnswer: "There is a headless horseman.",
          explanation: "The question asks what is present, and the answer confirms the presence of a headless horseman.",
          point: "20",
        },
      ],
    },

    {
      image: "https://picsum.photos/500",
      statement: "He has a problem.",
      questions: [
        {
          question: "Does he have a problem?",
          translation: "Uning muammosi bormi?",
          answer: "yes",
          messageForAnswer: "He has a problem.",
          explanation: "The question asks if he has a problem, and the answer confirms that he does.",
          point: "20",
        },
        {
          question: "Does he have a problem or a solution?",
          translation: "Uning muammosi yoki echimi bormi?",
          answer: "problem",
          messageForAnswer: "He has a problem.",
          explanation: "The question asks if he has a problem or a solution, and the answer confirms that he has a problem.",
          point: "20",
        },
        {
          question: "Does he have a solution?",
          translation: "Uning echimi bormi?",
          answer: "no",
          messageForAnswer: "He does not have a solution. He has a problem.",
          explanation: "The question asks if he has a solution, and the answer confirms that he does not, but he has a problem.",
          point: "20",
        },
        {
          question: "What does he have?",
          translation: "Uning nima bor?",
          answer: "He has a problem.",
          messageForAnswer: "He has a problem.",
          explanation: "The question asks what he has, and the answer confirms that he has a problem.",
          point: "20",
        },
      ],
    },
    {
      image: "https://picsum.photos/499",
      statement: "He goes to a doctor.",
      questions: [
        {
          question: "Does he go to a doctor?",
          translation: "U shifokorga boradimi?",
          answer: "yes",
          messageForAnswer: "He goes to a doctor.",
          explanation: "The question asks if he goes to a doctor, and the answer confirms that he does.",
          point: "20",
        },
        {
          question: "Does he go to a doctor or a dentist?",
          translation: "U shifokorga yoki tish shifokoriga boradimi?",
          answer: "doctor",
          messageForAnswer: "He goes to a doctor.",
          explanation: "The question asks if he goes to a doctor or a dentist, and the answer confirms that he goes to a doctor.",
          point: "20",
        },
        {
          question: "Does he go to a dentist?",
          translation: "U tish shifokoriga boradimi?",
          answer: "no",
          messageForAnswer: "He does not go to a dentist. He goes to a doctor.",
          explanation: "The question asks if he goes to a dentist, and the answer confirms that he does not, but he goes to a doctor instead.",
          point: "20",
        },
        {
          question: "Where does he go?",
          translation: "U qayerga boradi?",
          answer: "He goes to a doctor.",
          messageForAnswer: "He goes to a doctor.",
          explanation: "The question asks where he goes, and the answer confirms that he goes to a doctor.",
          point: "20",
        },
      ],
    },
    {
      image: "https://picsum.photos/498",
      statement: 'The doctor asks, "What\'s your problem?"',
      questions: [
        {
          question: 'Does the doctor ask, "What\'s your problem?"',
          translation: 'Shifokor, "Sizning muammoingiz nima?" deb so‘raydimi?',
          answer: "yes",
          messageForAnswer: 'The doctor asks, "What\'s your problem?"',
          explanation: "The question asks if the doctor inquires about the patient's problem, and the answer confirms that he does.",
          point: "20",
        },
        {
          question:
            'Does the doctor ask, "What\'s your problem?" or "How are you?"',
          translation:
            'Shifokor, "Sizning muammoingiz nima?" yoki "Qalaysiz?" deb so‘raydimi?',
          answer: '"What\'s your problem?"',
          messageForAnswer: 'The doctor asks, "What\'s your problem?"',
          explanation: "The question contrasts between two possible inquiries, and the answer confirms that the doctor asks about the problem.",
          point: "20",
        },
        {
          question: 'Does the doctor ask, "How are you?"',
          translation: 'Shifokor, "Qalaysiz?" deb so‘raydimi?',
          answer: "no",
          messageForAnswer: 'The doctor does not ask, "How are you?" The doctor asks, "What\'s your problem?"',
          explanation: "The question asks if the doctor inquires about general well-being, and the answer negates it, confirming that the doctor asks about the problem instead.",
          point: "20",
        },
        {
          question: "What does the doctor ask?",
          translation: "Shifokor nima deb so‘raydi?",
          answer: 'The doctor asks, "What\'s your problem?"',
          messageForAnswer: 'The doctor asks, "What\'s your problem?"',
          explanation: "The question asks what the doctor inquires about, and the answer confirms that the doctor asks about the problem.",
          point: "20",
        },
      ],
    },

    {
      image: "https://picsum.photos/497",
      statement: 'The headless horseman says, "I have a headache."',
      statement_aud:
        "/aud/025_the_headless_horseman_says_i_have_a_headache.mp3",
      questions: [
        {
          question: 'Does the headless horseman say, "I have a headache?"',
          translation:
            'Boshli chavandoz, "Mening boshim og\'riyapti" deb aytadimi?',
          answer: "yes",
          messageForAnswer: 'The headless horseman says, "I have a headache."',
          explanation: "The question asks if the headless horseman mentions having a headache, and the answer confirms that he does.",
          point: "20",
        },
        {
          question: 'Does the headless horseman say, "I have a headache" or "I have no head?"',
          translation: 'Boshli chavandoz, "Mening boshim og\'riyapti" yoki "Mening boshim yo\'q" deb aytadimi?',
          answer: '"I have a headache."',
          messageForAnswer: 'The headless horseman says, "I have a headache."',
          explanation: "The question contrasts two possible statements, and the answer confirms that the headless horseman mentions having a headache.",
          point: "20",
        },
        {
          question: 'Does the headless horseman say, "I have no head?"',
          translation: 'Boshli chavandoz, "Mening boshim yo\'q" deb aytadimi?',
          answer: "no",
          messageForAnswer: 'The headless horseman does not say, "I have no head." The headless horseman says, "I have a headache."',
          explanation: "The question asks if the headless horseman mentions not having a head, and the answer negates this, confirming that he says he has a headache instead.",
          point: "20",
        },
        {
          question: "What does the headless horseman say?",
          translation: "Boshli chavandoz nima deydi?",
          answer: 'The headless horseman says, "I have a headache."',
          messageForAnswer: 'The headless horseman says, "I have a headache."',
          explanation: "The question asks what the headless horseman says, and the answer confirms that he mentions having a headache.",
          point: "20",
        },
      ],
    },
  ],
};
