export const story1words = [
  {
    id: 1,
    front: "Sin cabeza",
    back: "without head / headless",
    image: "/img/headless-small.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 2,
    front: "Con cabeza",
    back: "with a head",
    image: "/img/headless-small.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 3,
    front: "Yo soy",
    back: "I am",
    image: "/img/horseman.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 4,
    front: "Tu eres",
    back: "You are",
    image: "/img/horseman.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 5,
    front: "Ella es",
    back: "She is",
    image: "/img/horseman.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 6,
    front: "El es",
    back: "He is",
    image: "/img/horseman.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 7,
    front: "Chica",
    back: "Girl",
    image: "/img/horseman.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 8,
    front: "Quién",
    back: "who",
    image: "/img/who.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 9,
    front: "Qué",
    back: "What",
    image: "/img/what.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 10,
    front: "Cómo",
    back: "How",
    image: "/img/what.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 11,
    front: "Hay",
    back: "There is",
    image: "/img/there_is.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 12,
    front: "Él tiene un problema.",
    back: "He has a problem.",
    image: "/img/problem.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },  
  {
    id: 13,
    front: "Está en Nueva York",
    back: "He is in New York",
    image: "/img/nyc.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 14,
    front: "Él va a",
    back: "He goes to",
    image: "/img/he_goes.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 15,
    front: "Al doctor",
    back: "The doctor",
    image: "/img/doctor.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 16,
    front: "Pregunta",
    back: "Ask(s)",
    image: "/img/asks.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 16,
    front: "Tu",
    back: "Your",
    image: "/img/you.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 17,
    front: "Él dice",
    back: "He says",
    image: "/img/he_says.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 18,
    front: "Yo tengo",
    back: "I have",
    image: "/img/i_have.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 19,
    front: "Dolor de",
    back: "Pain of",
    image: "/img/i_have.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 20,
    front: "Grande",
    back: "Big",
    image: "/img/big.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 21,
    front: "Casa",
    back: "House",
    image: "/img/house.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 22,
    front: "Hombre rico",
    back: "Rich man",
    image: "/img/rich_man.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 23,
    front: "Mil millones",
    back: "Billion",
    image: "/img/billion.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 24,
    front: "¿Puedes ayudarme?",
    back: "Can you help me?",
    image: "/img/you.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 25,
    front: "No puedo ayudar",
    back: "I cannot help",
    image: "/img/i_cant_help.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 26,
    front: "Puedo ayudar",
    back: "I can help",
    image: "/img/help.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 27,
    front: "Pequeño",
    back: "Small",
    image: "/img/small.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
  {
    id: 28,
    front: "Animales",
    back: "Animals",
    image: "/img/animals.jpg",
    difficulty: 0,
    due: new Date().toLocaleString(),
    elapsed_days: 0,
    lapses: 0,
    last_review: null,
    reps: 0,
    scheduled_days: 0,
    stability: 0,
    state: 0,
  },
];
